# Generated by Django 5.1.6 on 2025-03-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
