# Generated by Django 5.1.6 on 2025-03-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_department_employee_department'),
        ('employees', '0004_employee_archive_date'),
    ]

    operations = [
    ]
