# Generated by Django 5.1.6 on 2025-03-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_merge_20250327_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Department_name',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.department'),
        ),
    ]
