# Generated by Django 5.2 on 2025-04-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_profile_picture_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='seen_by_manager',
            field=models.BooleanField(default=False),
        ),
    ]
