# Generated by Django 5.2 on 2025-04-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_leaverequest_seen_by_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='seen_by_employee',
            field=models.BooleanField(default=False),
        ),
    ]
