# Generated by Django 5.1.6 on 2025-03-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='break_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
